fix awsconfig result processing by resource types
Optum/cloudig pull request #13
Opened 2021-08-13 07:33 UTC by Imunhatep

## Proposed changes
Fix resource type grouping for AWS Config. Current implementation pushes all resources under the first resource type.

## Issues for these changes
-

## Types of changes
- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [x ] I have filled out this PR template
- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, `CHANGELOG.md`, etc. - if appropriate)

## Dependencies and Blockers
none

## Relevant Links
-

## Further comments
Current results:
```
{
  "findings": [
    {
      "accountId": "0000000000000",
      "ruleName": "required-tags",
      "status": "NON_COMPLIANT",
      "flaggedResources": {
        "AWS::DynamoDB::Table": [1,2,3,4,5,6]
      }
}
```
After fix:
```
{
  "findings": [
    {
      "accountId": "0000000000000",
      "ruleName": "required-tags",
      "status": "NON_COMPLIANT",
      "flaggedResources": {
        "AWS::ACM::Certificate": [1,2,3],
        "AWS::AutoScaling::AutoScalingGroup": [1,2,3],
        "AWS::CloudFormation::Stack": [1,2,3],
        ...
        ],
    }
}
```

2021-08-13 07:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Optum/cloudig?pullRequest=13) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Optum/cloudig?pullRequest=13) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Optum/cloudig?pullRequest=13) it.</sub>

2021-08-13 14:43 UTC, bjfish25 commented
@Imunhatep Thanks for the contribution. Nice catch on this.

Can you add an entry in the the table test for [pkg/cloudig/awsconfig_test.go](https://github.com/Optum/cloudig/blob/master/pkg/cloudig/awsconfig_test.go#L156) for completeness.

Doesn't have to be complicated maybe something like ... and the corresponding output update.
```go
// L208
{
	ComplianceType: aws.String("NON_COMPLIANT"),
	ConfigRuleInvokedTime: timeHelper(2018, time.December, 21, 8, 38, 52, 0, time.UTC),
	EvaluationResultIdentifier: &configservice.EvaluationResultIdentifier {
		EvaluationResultQualifier: &configservice.EvaluationResultQualifier {
			ConfigRuleName: aws.String("ALL_OPEN_INBOUND_PORTS_SECURITY_GROUP_CHECK"),
			ResourceId: aws.String("sg-00004"),
			ResourceType: aws.String("AWS::EC2::SecurityGroup2"),
		},
		OrderingTimestamp: timeHelper(2018, time.December, 21, 8, 38, 36, 0, time.UTC),
	},
	ResultRecordedTime: timeHelper(2018, time.December, 21, 8, 38, 53, 0, time.UTC),
},
```

Afterwards, I can approve and merge.

2021-08-17 18:57 UTC, bjfish25 requested changes
@Imunhatep Good work on the output changes and the corresponding test.

A couple steps until we can merge
- sign the [contributing agreement](https://github.com/Optum/cloudig/pull/13#issuecomment-898252468)
  - You will likely have to consolidate your second commit to be signed by your github account
- add the awsconfig.go test, an example given [here](https://github.com/Optum/cloudig/pull/13#issuecomment-898506721)

2021-08-18 11:27 UTC, Imunhatep commented
Adding more tests is ok, but..

That is my personal account. There is a license, including forked repository. I won't sign anything, it's OSS - take it or leave it.

2021-08-20 01:12 UTC, shubydo reviewed
@Imunhatep Nice work! I had the same comments that @bjfish25 mentioned [here](https://github.com/Optum/cloudig/pull/13#pullrequestreview-732119655). After those pieces are addressed, we can get this fix merged.

2021-08-20 18:25 UTC, bjfish25 commented
> Adding more tests is ok, but..
> 
> That is my personal account. There is a license, including forked repository. I won't sign anything, it's OSS - take it or leave it.

@Imunhatep Sorry but we can't accept the addition unless you approve the contributors agreement. If not, thank you for your interest in cloudig and I'll make an issue on this topic so it can be fixed some time in the future.

2021-08-24 14:13 UTC, closed without merging

2021-08-24 14:14 UTC, Imunhatep commented
No problem. Thank you for looking into.