minor changes on the ECR code to view the report more precisely
Optum/cloudig pull request #15
Opened 2021-11-01 16:49 UTC by sainathdev

## Proposed changes

The Earlier code would show the report with and without vulnerabilities tags on the cloudreport. 
The code is now updated with two features
1. Get the Images and the tag of those only with the vulnerabilities and does not show the TAGs/Images without issues/vulnerabilities .
2. The code also shows the tags that with same SHA's as the comma separated tags. This mean when the same SHA of the image is used on the different environments, the image tag is now counted as a new vulnerabiliy.
-->

## Issues for these changes

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [ ] I have filled out this PR template
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, `CHANGELOG.md`, etc. - if appropriate)

## Dependencies and Blockers

## Relevant Links

## Further comments

2021-11-01 16:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Optum/cloudig?pullRequest=15) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Optum/cloudig?pullRequest=15) before we can accept your contribution.<br/><hr/>**Sainath Devulapally** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Optum/cloudig?pullRequest=15) it.</sub>

2021-11-01 17:19 UTC, sainathdev commented
[reportscan.log](https://github.com/Optum/cloudig/files/7455050/reportscan.log)

2021-11-01 17:21 UTC, sainathdev commented
@bjfish25 Updated the notes and added the log report as an example. Please review. Thank you.

2021-11-02 15:09 UTC, shubydo approved these changes

2021-11-02 21:22 UTC, sainathdev commented
> @sainathdev Can you update the doc page [here](https://github.com/Optum/cloudig/blob/master/doc/ecrscan.md) to include an example of a finding with an image that has more than one tag?

@shubydo  I have updated the md file. please review.

2021-11-02 23:26 UTC, bjfish25 requested changes
@sainathdev Can you fix your second commit, besides hat this looks good to merge

2021-11-03 01:02 UTC, shubydo requested changes

2021-11-03 01:02 UTC, shubydo commented on doc/ecrscan.md
> +|              |           | nonprod-2021-09-03.1, release-P8-1  |        | HIGH: 18               |             |
The output doesn't match here from what I get when running this locally. Each repository should have its own section, correct?

Ex:
```markdown
| ACCOUNT ID   | REGION    | REPOSITORY NAME             | TAG    | VULNERABILITIES(COUNT) | COMMENTS    |
|--------------|-----------|-----------------------------|--------|------------------------|-------------|
| 111111111111 | us-east-1 | dig/simple-server           | latest | MEDIUM:         8      | NEW_FINDING |
|              |           |                             |        | LOW:            1      |             |
|              |           |                             |        | HIGH:           2      |             |
|              |           | dig/sample-app              | latest | CRITICAL:       37     | NEW_FINDING |
|              |           |                             |        | HIGH:           67     |             |
|              |           |                             |        | MEDIUM:         164    |             |
|              |           |                             |        | LOW:            35     |             |
```

2021-11-03 01:16 UTC, shubydo commented on doc/ecrscan.md
> +|              |           | nonprod-2021-09-03.1, release-P8-1  |        | HIGH: 18               |             |
Also, this would be good to add as a test case [here](https://github.com/Optum/cloudig/blob/master/pkg/cloudig/output_test.go).

2021-11-09 17:36 UTC, shubydo approved these changes

2021-11-09 17:38 UTC, shubydo approved these changes

2021-11-09 17:57 UTC, bjfish25 approved these changes

2021-11-09 17:58 UTC, merged